services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: theseus_db
      POSTGRES_USER: theseus
      POSTGRES_PASSWORD: theseus
    volumes:
      - ./db_data/init.sql:/docker-entrypoint-initdb.d/init.sql

  webserver:
    image: nginx
    container_name: webserver
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/includes/:/etc/nginx/includes/
      - ./nginx/html:/usr/share/nginx/html/
    ports:
      - "8080:80"

  auth:
    image: quay.io/keycloak/keycloak:19.0.3
    container_name: auth
    volumes:
      - ./keycloak/data:/var/tmp
      - ./keycloak/startup-scripts/init.sh:/docker-entrypoint-sh/init.sh
    entrypoint: sh -c "/docker-entrypoint-sh/init.sh"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_PROXY: edge
    ports:
      - 8180:8180

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: mail@mail.com
      PGADMIN_DEFAULT_PASSWORD: pass
    depends_on:
      - postgres
    restart: always

volumes:
  db_data: